### PR TITLE
feature/bash

### PR DESCRIPTION
**Pull request by iConceali**

### CODE REVIEW

**Comment by manuelbarzi** [comment]
change base branch to develop

**Comment by manuelbarzi** [comment]
> change base branch to develop

i already did it

**Comment by PereHDZ** [comment]
You should change the language in #BASH to English

**Comment by xavigs89** [comment]
comments should be changed into English, please

**Comment by iConceali** [comment]
> > cambiar de rama base para desarrollar
> 
> ya lo hice



> Los comentarios deben cambiarse al inglés, por favor.

thank you! I already did.

**Comment by iConceali** [comment]
> Deberías cambiar el idioma en #BASH a inglés

thank you! I already did.

**Pull request merged**
